version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: formdb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: formdb
    depends_on:
      - db
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
